export const songsArray = [
    {
        name : "Enter City Limits",
        album: "the-solo-ep",
        fileName : "enter-city-limits",
        backgroundColor : "#ae1667",
        releaseDate : "January 15, 2021 00:00:00",
        iconColor : "dark",
        vimeoCode: "501270551",
    },
    {
        name : "A Brief History",
        album: "the-solo-ep",
        fileName : "a-brief-history",
        backgroundColor : "#ae1667",
        releaseDate : "January 15, 2021 00:00:00",
        iconColor : "dark",
        vimeoCode: "502747684",
    },
    {
        name : "And the Spirit Changes",
        album: "the-solo-ep",
        fileName : "and-the-spirit-changes",
        backgroundColor : "#ae1667",
        releaseDate : "January 15, 2021 00:00:00",
        iconColor : "dark",
        vimeoCode: "502748255",
    },
    {
        name : "War and Peace in the Land of Machines",
        album: "the-solo-ep",
        fileName : "war-and-peace-in-the-land-of-machines",
        backgroundColor : "#ae1667",
        releaseDate : "January 15, 2021 00:00:00",
        iconColor : "dark",
        vimeoCode: "501270704",
    },
    {
        name : "immortal in his own sense",
        album: "we-were-looking",
        fileName : "immortal-in-his-own-sense",
        backgroundColor : "#CACCFA",
        releaseDate : "February 24, 2021 00:00:00",
        iconColor : "dark",
        vimeoCode: "505304489",
    },
    {
        name : "he steps into a dark room",
        album: "we-were-looking",
        fileName : "he-steps-into-a-dark-room",
        backgroundColor : "#B8CBEA",
        releaseDate : "March 10, 2021 00:00:00",
        iconColor : "dark",
        vimeoCode: "505304778",
    },
    {
        name : "small, unnoticeable events",
        album: "we-were-looking",
        fileName : "small-unnoticeable-events",
        backgroundColor : "#CAD3FA",
        releaseDate : "March 24, 2021 00:00:00",
        iconColor : "dark",
        vimeoCode: "505304811",
    },
    {
        name : "pressed up against a wall of teenage angst",
        album: "we-were-looking",
        fileName : "pressed-up-against-a-wall-of-teenage-angst",
        backgroundColor : "#B4D9EB",
        releaseDate : "April 7, 2021 00:00:00",
        iconColor : "dark",
        vimeoCode: "505304852",
    },
    {
        name : "here is the world there is beyond",
        album: "we-were-looking",
        fileName : "here-is-the-world-there-is-beyond",
        backgroundColor : "#1C3954",
        releaseDate : "April 21, 2021 00:00:00",
        iconColor : "light",
        vimeoCode: "505304989",
    },
    {
        name : "kept on pushing and pushing and pushing",
        album: "we-were-looking",
        fileName : "kept-on-pushing-and-pushing-and-pushing",
        backgroundColor : "#023B58",
        releaseDate : "May 5, 2021 00:00:00",
        iconColor : "light",
        vimeoCode: "505305122",
    },
    {
        name : "as if it were some purified existence",
        album: "we-were-looking",
        fileName : "as-if-it-were-some-purified-existence",
        backgroundColor : "#182354",
        releaseDate : "May 19, 2021 00:00:00",
        iconColor : "light",
        vimeoCode: "505305148",
    },
    {
        name : "no tricks, not yet",
        album: "we-were-looking",
        fileName : "no-tricks-not-yet",
        backgroundColor : "#161730",
        releaseDate : "June 2, 2021 00:00:00",
        iconColor : "light",
        vimeoCode: "507729585",
    },
    {
        name : "angel, cut and cold",
        album: "we-were-looking",
        fileName : "angel-cut-and-cold",
        backgroundColor : "#17253D",
        releaseDate : "June 16, 2021 00:00:00",
        iconColor : "light",
        vimeoCode: "505305205",
    },
]